/**
 * MAA scenario catalog — Daphné's six rounds of conversational QA, plus
 * carry-over invariants from earlier passes that must never regress.
 *
 * Each scenario is tenantCode='maa' — strict tenant isolation. Adding new
 * tenant scenarios goes in a separate file (dubub.ts, future-tenant.ts).
 *
 * IDs are stable strings ("maa-6.1") so runner reports diff cleanly across
 * runs and CI can pin a specific scenario.
 */

import type { Scenario } from "./types.js";

const VISIT_CTA = /planifier une visite|schedule a visit|cliquez.*ci-dessous pour planifier votre visite/i;
const APPROX_PRICE = /\b(autour\s+de|environ|à\s+peu\s+pr[eè]s|approximately|around|approx\.?|roughly|about)\s+\$?\d/i;

export const MAA_SCENARIOS: Scenario[] = [
  // ── Phase 1 — Critical demo-blockers (Daphné sixth pass) ───────────────────
  {
    id: "maa-6.1",
    label: "Pickleball booking 'pickelball pour demain soir' — never visit CTA",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Est-ce que je peux booker un terrain de pickelball pour demain soir ?",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA, /Cliquez sur le bouton ci-dessous pour planifier votre visite/i],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/pickleball|terrain|disponibilit|réserv|reserv|équipe|team/i],
    phase: 1,
    source: "Daphné 6 #1 — 2/10",
    judgeRubric: {
      question:
        "Does the assistant suggest scheduling a club tour / visit / 'planifier une visite' to the user, instead of answering the pickleball reservation question?",
      expected: "no",
    },
  },
  {
    id: "maa-6.1b",
    label: "Pickleball booking variant 'pickball' — never visit CTA",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "je veux réserver un terrain de pickball demain soir",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA],
    requireSuppressBookingCta: true,
    phase: 1,
    source: "Daphné 6 #1 typo variant",
  },
  {
    id: "maa-6.1c",
    label: "Pickleball booking variant 'pickle ball' — never visit CTA",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "je veux booker un pickle ball court pour demain",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA],
    requireSuppressBookingCta: true,
    phase: 1,
    source: "Daphné 6 #1 typo variant 2",
  },
  {
    id: "maa-6.2",
    label: "Price contradiction 215 vs 225 — no 'autour de', no visit CTA",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "J'ai vu 215 $ sur votre site, mais tu m'as dit 225 $. Lequel est le bon ?",
    expectIntent: "price_contradiction",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA, APPROX_PRICE, /\bautour de\b/i],
    requirePatterns: [/225\s*\$/i],
    requireAnyPattern: [/source|confirm|équipe|valider|promotion/i],
    requireSuppressBookingCta: true,
    phase: 1,
    source: "Daphné 6 #2 — 4/10",
    judgeRubric: {
      question:
        "Does the assistant use approximation language like 'around', 'about', 'environ', 'autour de', or 'approximately' when stating the price?",
      expected: "no",
    },
  },
  {
    id: "maa-6.3",
    label: "Course count — must not invent '175 cours'",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "c'est quoi vos 75 cours offerts ?",
    forbidPatterns: [/\b175\s+(cours|classes|s[eé]ances)\b/i, /\b150\s+(cours|classes)\b/i, /\b200\s+(cours|classes)\b/i],
    requireAnyPattern: [/75|yoga|pilates|spin|aqua|HIIT|équipe|confirmer/i],
    phase: 1,
    source: "Daphné 6 #3 — 4/10",
  },
  {
    id: "maa-6.4",
    label: "Yoga à la carte — must not affirm without source",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Le yoga est inclus dans l'abonnement ou je peux payer juste un cours à la carte ?",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [
      /il (?:semble|me semble) (?:que ce soit|possible)/i,
      /il est aussi possible de participer à un ou quelques cours à la carte sans être membre/i,
      /vous pouvez (?:venir|essayer)\s+(?:à la carte|un seul cours)/i,
    ],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/abonnement|membership|équipe|validé|confirmer/i],
    phase: 1,
    source: "Daphné 6 #4 — 4/10",
    judgeRubric: {
      question:
        "Does the assistant suggest, imply, or affirm that à-la-carte / drop-in / single-class access for yoga is possible without an explicit source citation?",
      expected: "no",
    },
  },
  {
    id: "maa-6.5",
    label: "Knee pain — no medical diagnosis names",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "J'ai mal au genou et je veux savoir si je dois voir un physio ou un entraîneur.",
    expectIntent: "clinical_pain",
    forbidPatterns: [
      /\barthrite\b/i,
      /\bsyndrome\b/i,
      /\btendinite\b/i,
      /\bm[eé]nisque\s+d[eé]chir/i,
      /\bligament crois[eé]/i,
      /\bhernie discale\b/i,
      /\bsciatique\b/i,
      /\bpatella\b/i,
      /\brotule\b/i,
      /\bidéal/i,
      /généralement recommandée/i,
    ],
    requireAnyPattern: [/diagnostic|orient|équipe clinique|physiothérapie|thérapie sportive|confirmer/i],
    phase: 1,
    source: "Daphné 6 #5 — 5/10",
    judgeRubric: {
      question:
        "Does the assistant name a specific medical condition or diagnosis (e.g. arthritis, patellofemoral syndrome, tendinitis, torn meniscus, herniated disc, sciatica)?",
      expected: "no",
    },
  },

  // ── Phase 2 — Access and CTA precision ─────────────────────────────────────
  {
    id: "maa-6.6",
    label: "Gym time-slot — no invented reservation, no visit CTA",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je veux réserver un créneau au gym, pas une visite. C'est possible ?",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/sans réservation|membre|équipe|confirmer|exception/i],
    phase: 2,
    source: "Daphné 6 #6 — 3/10",
  },
  {
    id: "maa-6.7",
    label: "Quick info no form — must not push form, must not visit CTA",
    tenantCode: "maa",
    locale: "fr-CA",
    history: [
      { role: "user", content: "Combien coûte l'abonnement annuel ?" },
      {
        role: "assistant",
        content:
          "L'abonnement annuel commence à environ 225 $/mois. Souhaitez-vous que je transmette votre demande à l'équipe ?",
      },
    ],
    userMessage: "Je veux juste savoir vite, pas remplir un formulaire.",
    forbidFollowUpModes: ["callback", "calendly"],
    forbidPatterns: [VISIT_CTA, /entrez votre num[eé]ro/i, /remplir.*formulaire/i],
    phase: 2,
    source: "Daphné 6 #7 — 6/10",
  },
  {
    id: "maa-6.8",
    label: "Multi-category discount student / corporate / family — each answered",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Est-ce que vous offrez des rabais étudiants, corporatifs ou familiaux ?",
    requirePatterns: [/étudiant/i, /corporati/i, /famili/i],
    requireAnyPattern: [/confirm|équipe|185|sources?/i],
    phase: 2,
    source: "Daphné 6 #8 — 6/10",
    judgeRubric: {
      question:
        "Does the assistant address ALL THREE discount categories the user asked about — student, corporate, AND family — even if some are 'not confirmed in current sources'?",
      expected: "yes",
    },
  },
  {
    id: "maa-6.9",
    label: "Gym access no visit — do not guarantee, do not visit CTA",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je veux juste m'entraîner au gym, pas faire une visite. Est-ce que je peux accéder aux salles d'entraînement ?",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA, /vous pouvez venir sans problème/i],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/membre|non-?membre|équipe|confirm/i],
    phase: 2,
    source: "Daphné 6 #9 — 6/10",
  },
  {
    id: "maa-6.10",
    label: "Training rooms without reservation — clear member answer",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Est-ce que les salles d'entraînement sont accessibles sans réservation ou je dois booker un créneau ?",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/sans réservation|membre|accès|équipe/i],
    phase: 2,
    source: "Daphné 6 #10 — 7/10",
  },
  {
    id: "maa-6.11",
    label: "Pickleball non-member — clear answer, no visit CTA",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Pour le pickleball, est-ce que je peux réserver si je ne suis pas membre ?",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA, /je ne vois pas.*pickleball/i],
    requireSuppressBookingCta: true,
    phase: 2,
    source: "Daphné 6 #11 — 7/10",
  },
  {
    id: "maa-6.12",
    label: "Pickleball member-only or à la carte — clear answer",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Le pickleball, c'est réservé aux membres ou je peux venir à la carte ?",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA, /je ne vois pas.*pickleball/i],
    requireSuppressBookingCta: true,
    phase: 2,
    source: "Daphné 6 #12 — 7/10",
  },

  // ── Phase 3 — Service-specific quality ─────────────────────────────────────
  {
    id: "maa-6.13",
    label: "Weight loss program — prioritize trainer/nutrition, not massage first",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je veux perdre du poids et avoir un programme de remise en forme. Comment ça marche ?",
    forbidPatterns: [/^[^.!?]*massoth[eé]rapie/i, /^[^.!?]*massage/i],
    requireAnyPattern: [/entraîneur|trainer|nutrition|programme|cours|gym/i],
    phase: 3,
    source: "Daphné 6 #13 — 7/10",
    judgeRubric: {
      question:
        "Does the assistant lead with massage / physiotherapy as the primary recommendation for a weight-loss / fitness-program question, before mentioning personal training or nutrition?",
      expected: "no",
    },
  },
  {
    id: "maa-6.14",
    label: "Weight loss with typo 'progrsamme' — same handling",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "je veux perdre du poids et avoir un progrsamme de remise en forme. comment ca marche ?",
    requireAnyPattern: [/entraîneur|trainer|nutrition|programme|cours|gym/i],
    phase: 3,
    source: "Daphné 6 #14 — 7/10",
  },
  {
    id: "maa-6.15",
    label: "Membership inclusions — restaurant must NOT be listed as included",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Qu'est-ce qui est inclus dans l'abonnement au Club Sportif MAA ?",
    // Sentence-aware: forbid restaurant appearing in the SAME sentence as
    // "inclut" / "comprend" / "includes". A separate sentence about the
    // restaurant being on-site (paid separately) is allowed and expected.
    forbidPatterns: [
      /\binclut\b[^.!?]*\brestaurant\b/i,
      /\bcomprend\b[^.!?]*\brestaurant\b/i,
      /\bincludes?\b[^.!?]*\brestaurant\b/i,
      /\brestaurant\b[^.!?]*\b(?:inclus|comprend|inclu(?:s|t)?\s+dans\s+(?:l['']?)?(?:abonnement|membership))\b/i,
    ],
    requireAnyPattern: [/piscine|spa|gym|cours|squash|technogym/i],
    phase: 3,
    source: "Daphné 6 #15 — 8/10",
    judgeRubric: {
      question:
        "Does the assistant present the restaurant (Le 1881) as INCLUDED in the membership, instead of as an on-site amenity paid separately?",
      expected: "no",
    },
  },
  {
    id: "maa-6.16",
    label: "English pricing + booking — all English, no French CTA",
    tenantCode: "maa",
    locale: "en-CA",
    userMessage: "What are your prices and can I book in English?",
    forbidPatterns: [/planifier une visite/i, /\babonnement\b/i, /\btarifs\b/i, /\bcourriel\b/i],
    expectLanguage: "en",
    requireAnyPattern: [/\$\d|month|annual|membership/i],
    phase: 3,
    source: "Daphné 6 #16 — 8/10",
    judgeRubric: {
      question:
        "Is the assistant reply written ENTIRELY in English (no French sentences, no French CTA labels like 'Planifier une visite')?",
      expected: "yes",
    },
  },
  {
    id: "maa-6.17",
    label: "Modify plan no salesperson — respect preference, callback only",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je veux modifier mon forfait, mais je ne veux pas parler à un vendeur. Quelles sont mes options ?",
    expectIntent: "membership_downgrade",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [
      VISIT_CTA,
      /un vendeur va vous (?:rappeler|contacter|joindre)/i,
      /transfer.*sales/i,
      /équipe des ventes va/i,
    ],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/adhésion|équipe|validation|dossier|contrat/i],
    phase: 3,
    source: "Daphné 6 #17 — 8/10",
  },
  {
    id: "maa-6.18",
    label: "Spa with mother no membership — spa amenities not pool/pricing",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je veux aller au spa avec ma mère, mais on n'est pas membres. Est-ce possible ?",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [/L'adhésion comprend l'accès à la piscine/i, /Voici nos tarifs/i],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/spa|installations|membres|non-?membre|équipe|conditions/i],
    phase: 3,
    source: "Daphné 6 #18 — 8/10",
  },
  {
    id: "maa-6.19",
    label: "Mother-daughter spa package — must not invent",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Avez-vous un forfait spa détente mère-fille même si je n'ai pas d'abonnement ?",
    forbidPatterns: [/oui, nous (?:avons|proposons|offrons) un forfait mère-fille/i],
    requireAnyPattern: [/je ne vois pas|valider|équipe|confirmer|sources actuelles/i],
    phase: 3,
    source: "Daphné 6 #19 — 8/10",
  },
  {
    id: "maa-6.20",
    label: "Restaurant menu this week — must include real link",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "pis est-ce que je peux savoir vos menus cette semaine pour le resto",
    requireAnyPattern: [/\[.+\]\(https?:\/\//i, /clubsportifmaa\.com/i],
    forbidPatterns: [/le menu n'est pas (?:publié|disponible)/i],
    phase: 3,
    source: "Daphné 6 #20 — 8/10",
  },
  {
    id: "maa-6.21",
    label: "Vague circus request — ask one clarification",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "jaurais une demande concernant le cirque",
    requireAnyPattern: [/horaire|niveau|inscription|âge|débutant|prix|précis/i],
    phase: 3,
    source: "Daphné 6 #21 — 8/10",
  },
  {
    id: "maa-6.22",
    label: "Group classes included — direct yes first",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Est-ce que l'abonnement donne accès aux cours de groupe ?",
    requireAnyPattern: [/oui|inclus|donne accès|comprend/i],
    phase: 3,
    source: "Daphné 6 #22 — 8/10",
  },
  {
    id: "maa-6.23",
    label: "Pickleball weekly availability — say must confirm",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Le pickleball a combien de disponibilités par semaine environ ?",
    forbidPatterns: [/je ne vois pas.*pickleball/i, /ne propose pas.*pickleball/i],
    requireAnyPattern: [/confirmer|équipe|horaire|disponibilit/i],
    phase: 3,
    source: "Daphné 6 #23 — 8/10",
  },
  {
    id: "maa-6.24",
    label: "Buanderie included or extra — use confirmed price if source has it",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "La buanderie est-tu incluse avec mon abonnement ou je dois payer en plus ?",
    forbidPatterns: [/je ne vois pas.*buanderie/i, VISIT_CTA],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/buanderie|service|équipe|confirmer/i],
    phase: 3,
    source: "Daphné 6 #24 — 9/10",
  },

  // ── Phase 4 — DO NOT REGRESS (9/10 and 10/10 cases) ────────────────────────
  {
    id: "maa-6.25",
    label: "Buanderie typo 'buandrie' — must NOT deny",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "avez vous un service de buandrie?",
    forbidPatterns: [/je ne vois pas.*buanderie/i, /ne propose pas.*buanderie/i, VISIT_CTA],
    requireSuppressBookingCta: true,
    phase: 4,
    source: "Daphné 6 #25 — 9/10 KEEP",
  },
  {
    id: "maa-6.26",
    label: "Laundry 'lavage' wording — recognized as buanderie",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je veux faire mon lavage au club, comment ça marche",
    forbidPatterns: [/laverie publique|public laundromat/i, VISIT_CTA],
    requireSuppressBookingCta: true,
    phase: 4,
    source: "Daphné 6 #26 — 9/10 KEEP",
  },
  {
    id: "maa-6.27",
    label: "Technogym evaluation — answer about Technogym, not price grid",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Est-ce que l'évaluation Technogym est incluse avec l'abonnement ?",
    forbidPatterns: [/Voici nos tarifs/i, VISIT_CTA],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/technogym|évaluation|checkup|équipe|confirmer/i],
    phase: 4,
    source: "Daphné 6 #27 — 9/10 KEEP",
  },
  {
    id: "maa-6.28",
    label: "Technogym Checkup included or separate — cautious",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je veux faire le Technogym Checkup. Est-ce que c'est inclus ou je dois payer séparément ?",
    forbidPatterns: [/Voici nos tarifs/i, VISIT_CTA],
    requireSuppressBookingCta: true,
    phase: 4,
    source: "Daphné 6 #28 — 9/10 KEEP",
  },
  {
    id: "maa-6.29",
    label: "'oui' after clinical handoff — advance, do not re-triage",
    tenantCode: "maa",
    locale: "fr-CA",
    history: [
      {
        role: "user",
        content: "J'ai mal au dos, qu'est-ce que vous recommandez ?",
      },
      {
        role: "assistant",
        content:
          "Je ne peux pas poser de diagnostic, mais l'équipe clinique du Club — physiothérapie ou thérapie sportive — peut être un bon point de départ. Souhaitez-vous que je transmette votre demande ?",
      },
    ],
    userMessage: "oui",
    forbidPatterns: [/Je ne peux pas (?:poser|faire) de diagnostic/i],
    requireAnyPattern: [/nom|téléphone|courriel|coordonn|email|phone|name/i],
    phase: 4,
    source: "Daphné 6 #29 — 9/10 KEEP",
  },
  {
    id: "maa-6.30",
    label: "Membership too expensive, lower without visit — model response",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Mon abonnement coûte trop cher, je veux le baisser sans prendre rendez-vous pour une visite.",
    expectIntent: "membership_downgrade",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/équipe|adhésion|valider|callback|rappel|transmettre/i],
    phase: 4,
    source: "Daphné 6 #30 — 10/10 KEEP",
  },
  {
    id: "maa-6.31",
    label: "Current membership downgrade — model response",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je peux changer mon abonnement actuel pour un abonnement plus bas ?",
    expectIntent: "membership_downgrade",
    forbidFollowUpModes: ["calendly", "vapi"],
    forbidPatterns: [/^Bien sûr\. Utilisez le bouton ci-dessous pour continuer par téléphone/i, VISIT_CTA],
    requireSuppressBookingCta: true,
    phase: 4,
    source: "Daphné 6 #31 — 10/10 KEEP",
  },
  {
    id: "maa-6.32",
    label: "Cancellation typo 'e veux annuler' — must still detect cancellation",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "e veux annuler mon abonnement",
    expectIntent: "cancellation",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA],
    requireSuppressBookingCta: true,
    phase: 4,
    source: "Daphné 6 #32 — 10/10 KEEP",
  },
  {
    id: "maa-6.33",
    label: "Uppercase cancellation 'JE VEUX ANNULER' — must still detect",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "JE VEUX ANNULER",
    expectIntent: "cancellation",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA],
    requireSuppressBookingCta: true,
    phase: 4,
    source: "Daphné 6 #33 — 10/10 KEEP",
  },

  // ── Seventh-pass scenarios ────────────────────────────────────────────────
  // Phase 1 — Pickleball schedule routing (the biggest seventh-pass miss)
  {
    id: "maa-7.4",
    label: "Pickleball schedule typo 'pickeball' — must NOT return club/pool/spa hours",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "C'est quoi les horaires pour pickeball",
    forbidPatterns: [
      /horaires?\s+du?\s+club\s*:/i,
      /horaires?\s+de\s+la\s+piscine/i,
      /horaires?\s+du\s+spa/i,
      /\bL[Uu]ndi\s+à\s+vendredi\s+de\s+6h\s+à\s+22h/i,
    ],
    requireAnyPattern: [/pickleball|28\s+(?:cases|timeslots)|membre/i],
    requireSuppressBookingCta: true,
    phase: 1,
    source: "Daphné 7 #4 — 3/10",
    judgeRubric: {
      question:
        "Does the assistant answer with the GENERAL club / pool / spa hours instead of pickleball-specific schedule information?",
      expected: "no",
    },
  },
  {
    id: "maa-7.3",
    label: "Pickleball weekly availability — must give 28 timeslots",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Le pickleball a combien de disponibilités par semaine environ ?",
    forbidPatterns: [/je ne vois pas.*pickleball/i],
    requireAnyPattern: [/28|cases\s+horaires|plages|disponibilit/i],
    requireSuppressBookingCta: true,
    phase: 1,
    source: "Daphné 7 #3 — 0/10",
  },
  {
    id: "maa-7.2",
    label: "Book pickleball for tomorrow night — answer pickleball-specifically",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Est-ce que je peux booker un terrain de pickelball pour demain soir ?",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA, /^Bonjour Daphné/i, /horaires?\s+(?:du club|de la piscine|du spa)/i],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/membre|réserv|2\s+(?:à|to)\s+4|équipe/i],
    phase: 1,
    source: "Daphné 7 #2 — 0/10",
  },

  // Phase 2 — Conversation quality
  {
    id: "maa-7.1",
    label: "Vague circus request — must ask clarification first",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "jaurais une demande concernant le cirque",
    forbidPatterns: [
      /Le Club Sportif MAA propose un programme de cirque aérien parmi ses cours/i,
      /plus de 75 cours/i,
    ],
    requireAnyPattern: [/horaire|inscription|niveau|âge|disponibilit|précis/i],
    requireFollowUpMode: ["clarify"],
    phase: 2,
    source: "Daphné 7 #1 — 0/10",
    judgeRubric: {
      question:
        "Does the assistant launch into a generic circus description instead of asking ONE clarification question about what the user wants (schedule, registration, levels, age, availability)?",
      expected: "no",
    },
  },
  {
    id: "maa-7.8",
    label: "Restaurant included — no broken grammar 'Daphné est situé'",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Si je prends l'abonnement, est-ce que le restaurant Le 1881 est inclus dans le prix ?",
    forbidPatterns: [
      /^Daphné\s+est\s+(?:bien\s+)?situé/i,
      /^Daphné\s+est\s+(?:bien\s+)?(?:disponible|inclus|offert)/i,
    ],
    requireAnyPattern: [/restaurant|1881|sur place|payé séparément|paid separately/i],
    phase: 2,
    source: "Daphné 7 #8 — 7/10 grammar",
    judgeRubric: {
      question:
        "Does the assistant start with a grammatically broken sentence like 'Daphné est bien situé' where the user's name is incorrectly used as the subject of a verb meant for the restaurant?",
      expected: "no",
    },
  },
  {
    id: "maa-7.9",
    label: "Quick info no form — must NOT invent gym topic out of nowhere",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je veux juste savoir vite, pas remplir un formulaire.",
    forbidFollowUpModes: ["callback"],
    forbidPatterns: [
      /pour réserver un créneau au gym/i,
      /créneau au gym, il n'y a pas/i,
      VISIT_CTA,
    ],
    requireSuppressBookingCta: true,
    phase: 2,
    source: "Daphné 7 #9 — 6/10",
    judgeRubric: {
      question:
        "Does the assistant invent a topic (like 'gym slot reservation') that the user never mentioned, instead of asking ONE short clarification question?",
      expected: "no",
    },
  },

  // Phase 3 — CTA polish
  {
    id: "maa-7.5",
    label: "Yoga à la carte — must NOT show 'Planifier une visite' CTA",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je veux juste faire un cours de yoga à la carte sans abonnement, c'est possible ?",
    forbidPatterns: [VISIT_CTA, /Prochaine étape \? → Planifier une visite/i],
    requireSuppressBookingCta: true,
    phase: 3,
    source: "Daphné 7 #5 — 7/10 CTA",
  },
  {
    id: "maa-7.6",
    label: "Discount question — must NOT show 'Planifier une visite' CTA",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Avez-vous des rabais étudiants, corporatifs, familiaux et pour les aînés ?",
    forbidPatterns: [VISIT_CTA, /Prochaine étape \? → Planifier une visite/i],
    requirePatterns: [/étudiant/i, /corporati/i, /famili/i],
    requireSuppressBookingCta: true,
    phase: 3,
    source: "Daphné 7 #6 — 7/10 CTA",
  },
  {
    id: "maa-7.10",
    label: "Gym access — must NOT guarantee access when membership unknown",
    tenantCode: "maa",
    locale: "fr-CA",
    userMessage: "Je veux juste m'entraîner au gym, pas faire une visite. Est-ce que je peux accéder aux salles d'entraînement ?",
    forbidFollowUpModes: ["calendly"],
    forbidPatterns: [VISIT_CTA, /^[^.!?]*\bvous pouvez accéder\b(?![^.!?]*membre)/i],
    requireSuppressBookingCta: true,
    requireAnyPattern: [/membre|non-?membre|équipe|conditions/i],
    phase: 3,
    source: "Daphné 7 #10 — 7/10",
  },
];
